=== helgoboss/jampad-public/antora/modules/ROOT/attachments/jampad-space-export.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://jampad.app/schemas/jampad-space-export.schema.json",
  "title": "Jam Pad Space Export",
  "description": "The format in which Jam Pad exports a single space",
  "$ref": "#/definitions/Space",
  "definitions": {
    "Space": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "title": "Space",
      "description": "All contents of a single Jam Pad space that are not user/device-specific",
      "properties": {
        "customFieldsForFiles": {
          "type": "array",
          "description": "All custom fields usable for recordings",
          "items": {
            "$ref": "#/definitions/CustomField"
          }
        },
        "customFieldsForMarkers": {
          "type": "array",
          "description": "All custom fields usable for markers",
          "items": {
            "$ref": "#/definitions/CustomField"
          }
        },
        "customItemTypes": {
          "description": "All types of custom items usable for custom fields",
          "type": "array",
          "items": {
            "$ref": "#/definitions/CustomItemType"
          }
        },
        "customItems": {
          "description": "All custom items usable for custom fields. Each map key must be the ID of a custom item type. Each value must be the list of custom items.",
          "type": "object",
          "additionalProperties": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CustomItem"
            }
          }
        },
        "files": {
          "description": "All recordings",
          "type": "array",
          "items": {
            "$ref": "#/definitions/MediaFile"
          }
        },
        "markers": {
          "description": "All markers",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Marker"
          }
        },
        "playlists": {
          "description": "All playlists",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Playlist"
          }
        },
        "sheets": {
          "description": "All sheets",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Sheet"
          }
        }
      }
    },
    "CustomField": {
      "type": "object",
      "required": ["id", "name", "type"],
      "title": "Custom field",
      "description": "A custom field usable for recordings or markers, depending in which list it appears",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "Identifier of the custom field. Must be unique within this space."
        },
        "hidden": {
          "type": "boolean",
          "description": "Whether this field is hidden",
          "default": false
        },
        "position": {
          "type": "integer",
          "description": "Position of this field relative to other fields. Influences where it appears in the Jam Pad user interface.",
          "default": 1000
        },
        "showInListView": {
          "type": "boolean",
          "description": "Whether this field should show up in Jam Pad's list views (vs. only in the detail views).",
          "default": false
        },
        "name": {
          "type": "string",
          "description": "Field name"
        },
        "description": {
          "type": "string",
          "description": "Explains the purpose of this field"
        },
        "type": {
          "enum": ["string", "note", "tonalQuality", "bpm", "timeSignature", "item", "items"],
          "description": "Defines which type of values this field accepts and how Jam Pad displays them"
        },
        "itemTypeId": {
          "type": "string",
          "description": "For type 'item' and 'items', this defines the collection of choices among which users may pick"
        }
      }
    },
    "CustomItemType": {
      "type": "object",
      "required": ["id", "name"],
      "title": "Custom item type",
      "description": "Defines a possible collection of items. The actual items for the collection are not yet defined.",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "Identifier of the custom item type. Must be unique within this space."
        },
        "hidden": {
          "type": "boolean",
          "description": "Whether this item collection is hidden",
          "default": false
        },
        "name": {
          "type": "string",
          "description": "Item collection name"
        }
      }
    },
    "CustomItem": {
      "type": "object",
      "required": ["id", "name"],
      "title": "Custom item",
      "description": "Defines an actual custom item belonging to the surrounding collection.",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "Identifier of the custom item. Must be unique within this collection."
        },
        "hidden": {
          "type": "boolean",
          "description": "Whether this item is hidden",
          "default": false
        },
        "name": {
          "type": "string",
          "description": "Item name"
        },
        "customColor": {
          "description": "Defines a custom color in which this item will be appear.",
          "$ref": "#/definitions/CustomColor"
        },
        "paletteColor": {
          "description": "Picks a color from a dynamic palette. Only applied if no custom color is given.",
          "type": "integer"
        }
      }
    },
    "CustomColor": {
      "title": "Custom color",
      "description": "Defines a custom RGB color",
      "type": "array",
      "items": [
        { "type": "integer", "minimum": 0, "maximum": 255, "description": "Amount of red" },
        { "type": "integer", "minimum": 0, "maximum": 255, "description": "Amount of green"  },
        { "type": "integer", "minimum": 0, "maximum": 255, "description": "Amount of blue"  }
      ],
      "minItems": 3,
      "maxItems": 3
    },
    "MediaFile": {
      "title": "Recording",
      "description": "Describes a recording",
      "type": "object",
      "required": ["path"],
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to the actual media file. This path must be relative to the directory in which the JSON file is located."
        },
        "authorId": {
          "type": "integer",
          "description": "TODO"
        },
        "hidden": {
          "type": "boolean",
          "description": "Whether this recording is hidden",
          "default": false
        },
        "name": {
          "type": "string",
          "description": "Name of the recording",
          "default": "Metadata title or file name of the actually imported file"
        },
        "recordedAt": {
          "type": "integer",
          "$ref": "#/definitions/Timestamp",
          "description": "Certain timestamp that says when this recording was initially recorded"
        },
        "origin": {
          "enum": ["imported", "recorded"],
          "description": "Whether this recording was recorded directly within Jam Pad or imported from outside",
          "default": "imported"
        },
        "importInstallationId": {
          "type": "string",
          "format": "uuid",
          "description": "If imported, this field contains a globally unique identifier that says in which specific Jam Pad installation this recording has been originally imported.",
          "default": "ID of the Jam Pad installation which is importing this JSON file"
        },
        "importId": {
          "type": "string",
          "format": "uuid",
          "description": "If imported, this field contains a globally unique identifier that says by which specific original import job this recording has been imported.",
          "default": "ID of the import with which this JSON file is being imported"
        },
        "importBaseFolderHash": {
          "type": "string",
          "description": "If imported, this field contains a cryptic string that says from which absolute base path the original import was started. It's cryptic for a reason: In collaborative spaces, this string will be visible to all space members. To protect the original importer's privacy, we don't save the base folder in plain text (it could contain an OS username)."
        },
        "importBaseFolderName": {
          "type": "string",
          "description": "If imported, this field contains the name of the folder from which the original import was started."
        },
        "importPath": {
          "type": "string",
          "description": "If imported, this field contains the relative path from which this media was originally imported.",
          "default": "Same as 'path'"
        },
        "importContentHash": {
          "type": "string",
          "description": "If imported, this field contains the unique fingerprint of the originally imported file.",
          "default": "Hash of the actual file that is being imported"
        },
        "importFormat": {
          "enum": ["wav", "mp3", "fac", "m4a"],
          "description": "If imported, this field contains the format of the originally imported file.",
          "default": "Format of the actual file that is being imported"
        },
        "customData": {
          "$ref": "#/definitions/CustomData",
          "description": "Custom data associated with this recording"
        }
      }
    },
    "Timestamp": {
      "type": "integer",
      "description": "Timezone-less timestamp, expressed in milliseconds since epoch UTC"
    },
    "CustomData": {
      "type": "object",
      "title": "Custom data",
      "description": "Arbitrary data. Each key of this object corresponds to the ID of a custom field. If the custom field doesn't exist, the data will be kept but not shown in the user interface. The structure of the value must correspond to the type of the custom field. It can be anything from a simple number to a complex nested object.",
      "additionalProperties": true
    },
    "Marker": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "authorId": {
          "type": "integer"
        },
        "hidden": {
          "type": "boolean"
        },
        "fileId": {
          "type": "string"
        },
        "filePath": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "start": {
          "type": "integer"
        },
        "length": {
          "type": "integer"
        },
        "rating": {
          "type": "integer"
        },
        "createdAt": {
          "type": "integer"
        },
        "comments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Comment"
          }
        },
        "customData": {
          "$ref": "#/definitions/MarkerCustomData"
        }
      },
      "required": [],
      "title": "Marker"
    },
    "Comment": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "hidden": {
          "type": "boolean"
        },
        "authorId": {
          "type": "integer"
        },
        "createdAt": {
          "type": "integer"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [],
      "title": "Comment"
    },
    "MarkerCustomData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "019951f6-fa46-7b80-b4c8-54801c12a8b0": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [],
      "title": "MarkerCustomData"
    },
    "Playlist": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "hidden": {
          "type": "boolean"
        },
        "authorId": {
          "type": "integer"
        },
        "createdAt": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [],
      "title": "Playlist"
    },
    "Sheet": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "hidden": {
          "type": "boolean"
        },
        "title": {
          "type": "string"
        },
        "content": {
          "$ref": "#/definitions/SheetContent"
        }
      },
      "required": [],
      "title": "Sheet"
    },
    "SheetContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PurpleContent"
          }
        }
      },
      "required": [],
      "title": "SheetContent"
    },
    "PurpleContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FluffyContent"
          }
        },
        "attrs": {
          "$ref": "#/definitions/PurpleAttrs"
        }
      },
      "required": [],
      "title": "PurpleContent"
    },
    "PurpleAttrs": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "level": {
          "type": "integer"
        }
      },
      "required": [],
      "title": "PurpleAttrs"
    },
    "FluffyContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TentacledContent"
          }
        }
      },
      "required": [],
      "title": "FluffyContent"
    },
    "TentacledContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StickyContent"
          }
        }
      },
      "required": [],
      "title": "TentacledContent"
    },
    "StickyContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "attrs": {
          "$ref": "#/definitions/FluffyAttrs"
        }
      },
      "required": [],
      "title": "StickyContent"
    },
    "FluffyAttrs": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "href": {
          "type": "string"
        }
      },
      "required": [],
      "title": "FluffyAttrs"
    }
  }
}

=== helgoboss/jampad-public/antora/modules/ROOT/examples/jampad-export-nature-and-music.json
{
    "customFieldsForFiles": [
        {
            "id": "moods",
            "hidden": false,
            "name": "Moods",
            "type": "items",
            "itemTypeId": "moods",
            "description": "Associate a file or marker with moods or emotions, such as \"Happy\" or \"Sad\"",
            "position": 600,
            "showInListView": true
        },
        {
            "id": "tonalCenter",
            "hidden": false,
            "name": "Tonal center",
            "type": "note",
            "description": "Tonal center (or root note) of a musical piece, for example D♭. Together with the *Tonal quality* field, it makes up the key of a musical piece.",
            "position": 30,
            "showInListView": true
        },
        {
            "id": "tonalQuality",
            "hidden": false,
            "name": "Tonal quality",
            "type": "tonalQuality",
            "description": "Tonal quality of a musical piece, that is, *major* or *minor*. If you need more variety, consider adding a *Scales/modes* field.",
            "position": 31,
            "showInListView": true
        }
    ],
    "customFieldsForMarkers": [
        {
            "id": "019951f6-fa46-7b80-b4c8-54801c12a8b0",
            "hidden": false,
            "name": "Sound source",
            "type": "item",
            "itemTypeId": "019951f6-fa45-7c09-a569-22d90f660df3",
            "position": 1000,
            "showInListView": true
        }
    ],
    "customItemTypes": [
        {
            "id": "moods",
            "hidden": false,
            "name": "Moods"
        },
        {
            "id": "019951f6-fa45-7c09-a569-22d90f660df3",
            "hidden": false,
            "name": "Sound source"
        }
    ],
    "customItems": {
        "moods": [
            {
                "id": "019951f4-bfd2-7fe8-a227-ddd6e19c29e5",
                "hidden": false,
                "name": "Dreamy",
                "customColor": [
                    148,
                    103,
                    189
                ]
            },
            {
                "id": "019951f4-f46f-7693-b179-99734860774c",
                "hidden": false,
                "name": "Rigid",
                "customColor": [
                    23,
                    190,
                    207
                ]
            }
        ],
        "019951f6-fa45-7c09-a569-22d90f660df3": [
            {
                "id": "019951f7-1514-7dfc-9c79-e5c7ec9b761c",
                "hidden": false,
                "name": "Cricket",
                "customColor": [
                    255,
                    127,
                    14
                ]
            },
            {
                "id": "019951f9-1ed2-714f-be12-163b97bf1b22",
                "hidden": false,
                "name": "Stones",
                "customColor": [
                    188,
                    189,
                    34
                ]
            }
        ]
    },
    "files": [
        {
            "path": "assets/7SA8JQ5SRM97H2XC4075TWRRG4-media.m4a",
            "authorId": 0,
            "hidden": false,
            "name": "Siquijor Hill",
            "origin": "imported",
            "importInstallationId": "01991a04-8640-7820-b3bf-3da3754cf705",
            "importId": "019951ae-4098-7ddf-822c-a22ebd3246e0",
            "importBaseFolderHash": "5A6JFGW2HZ3SB3E6KTCCW42RR8",
            "importBaseFolderName": "docs",
            "importPath": "230212-142536-siquijor-hill.wav",
            "importContentHash": "4JRKZ1T9SPS035M0KZ36SRHXEG",
            "importFormat": "wav",
            "customData": {}
        },
        {
            "path": "assets/8E4CN8JX590DTMPA5MFM76HGC4-media.mp3",
            "authorId": 0,
            "hidden": false,
            "name": "Distance",
            "origin": "imported",
            "importInstallationId": "01991a04-8640-7820-b3bf-3da3754cf705",
            "importId": "019951ae-4098-7ddf-822c-a22ebd3246e0",
            "importBaseFolderHash": "5A6JFGW2HZ3SB3E6KTCCW42RR8",
            "importBaseFolderName": "docs",
            "importPath": "Distance.mp3",
            "importContentHash": "8E4CN8JX590DTMPA5MFM76HGC4",
            "importFormat": "mp3",
            "customData": {
                "tonalCenter": "B♭",
                "tonalQuality": "min",
                "moods": {
                    "019951f4-bfd2-7fe8-a227-ddd6e19c29e5": null
                }
            }
        },
        {
            "path": "assets/TT9Q3E82VZN64VY1YP0CF76AR4-media.m4a",
            "authorId": 0,
            "hidden": false,
            "name": "Rügen Sea",
            "origin": "imported",
            "importInstallationId": "01991a04-8640-7820-b3bf-3da3754cf705",
            "importId": "019951eb-b050-7b1f-961e-c669e7657e70",
            "importBaseFolderHash": "5A6JFGW2HZ3SB3E6KTCCW42RR8",
            "importBaseFolderName": "docs",
            "importPath": "ruegen.WAV",
            "importContentHash": "D4GPJ595FT4EVB56M1H99NC76C",
            "importFormat": "wav",
            "customData": {}
        },
        {
            "path": "assets/R00YRM97VVK5M9MSBT9RAVSECG-media.m4a",
            "authorId": 0,
            "hidden": false,
            "name": "Whistling",
            "recordedAt": 1758012017571,
            "origin": "recorded",
            "customData": {}
        }
    ],
    "markers": [
        {
            "id": "019951e5-2158-7455-9435-5e9dfbe83a6f",
            "authorId": 0,
            "hidden": false,
            "fileId": "8E4CN8JX590DTMPA5MFM76HGC4",
            "filePath": "assets/8E4CN8JX590DTMPA5MFM76HGC4-media.mp3",
            "name": "Distorted",
            "start": 153909,
            "length": 15000,
            "rating": 2,
            "createdAt": 1758015594840,
            "comments": [],
            "customData": {}
        },
        {
            "id": "019951e3-c263-7d6e-96ab-0acdc0511c1b",
            "authorId": 0,
            "hidden": false,
            "fileId": "7SA8JQ5SRM97H2XC4075TWRRG4",
            "filePath": "assets/7SA8JQ5SRM97H2XC4075TWRRG4-media.m4a",
            "name": "Loud cricket",
            "start": 254634,
            "length": 15000,
            "rating": 4,
            "createdAt": 1758015504995,
            "comments": [
                {
                    "id": "019951f1-724d-74b6-9245-104e6fb00b68",
                    "hidden": false,
                    "authorId": 0,
                    "createdAt": 1758016401997,
                    "content": "What an awesome cricket sound!"
                }
            ],
            "customData": {
                "019951f6-fa46-7b80-b4c8-54801c12a8b0": "019951f7-1514-7dfc-9c79-e5c7ec9b761c"
            }
        },
        {
            "id": "019951e4-22aa-78e2-a8e8-4a36823d63aa",
            "authorId": 0,
            "hidden": false,
            "fileId": "8E4CN8JX590DTMPA5MFM76HGC4",
            "filePath": "assets/8E4CN8JX590DTMPA5MFM76HGC4-media.mp3",
            "name": "Drop & Flute",
            "start": 98404,
            "length": 15000,
            "createdAt": 1758015529643,
            "comments": [],
            "customData": {}
        },
        {
            "id": "019951f8-317b-7f96-a3ea-652e7e9bf8d0",
            "authorId": 0,
            "hidden": false,
            "fileId": "TT9Q3E82VZN64VY1YP0CF76AR4",
            "filePath": "assets/TT9Q3E82VZN64VY1YP0CF76AR4-media.m4a",
            "name": "Knocking stones",
            "start": 36123,
            "length": 15000,
            "createdAt": 1758016844155,
            "comments": [],
            "customData": {
                "019951f6-fa46-7b80-b4c8-54801c12a8b0": "019951f9-1ed2-714f-be12-163b97bf1b22"
            }
        }
    ],
    "playlists": [
        {
            "id": "019951ef-58e7-707a-8a8c-ac511b84a591",
            "hidden": false,
            "authorId": 0,
            "createdAt": 1758016264423,
            "name": "Nature",
            "items": [
                "/marker/019951e4-22aa-78e2-a8e8-4a36823d63aa#6DHP",
                "/marker/019951e3-c263-7d6e-96ab-0acdc0511c1b#PA5X",
                "/file/7SA8JQ5SRM97H2XC4075TWRRG4#TYCX"
            ]
        }
    ],
    "sheets": [
        {
            "id": "home",
            "hidden": false,
            "title": "Home",
            "content": {
                "type": "doc",
                "content": [
                    {
                        "type": "paragraph",
                        "content": [
                            {
                                "type": "text",
                                "text": "This space is all about nature. Field recordings mixed with music deeply connected to the natural world."
                            }
                        ]
                    },
                    {
                        "type": "heading",
                        "attrs": {
                            "id": "0HPS",
                            "level": 2
                        },
                        "content": [
                            {
                                "type": "text",
                                "text": "Some examples"
                            }
                        ]
                    },
                    {
                        "type": "bulletList",
                        "content": [
                            {
                                "type": "listItem",
                                "content": [
                                    {
                                        "type": "paragraph",
                                        "content": [
                                            {
                                                "type": "jam",
                                                "attrs": {
                                                    "id": "EYPX",
